version: '3'

services:
  # https://github.com/vimagick/dockerfiles
  dante:
    image: vimagick/dante:latest
    container_name: dante
    ports:
      - "1088:1080"
    volumes:
      - "./dante-entrypoint.sh:/dante-entrypoint.sh"
      - ./sockd.conf:/etc/sockd.conf
    environment:
      - CFGFILE=/etc/sockd.conf
      - PIDFILE=/tmp/sockd.pid
      - WORKERS=10
      - SOCKS_USERNAME=suck-rkn
      - SOCKS_PASSWORD=telegram
    restart: unless-stopped
    command: bash /dante-entrypoint.sh

  # https://github.com/kylemanna/docker-openvpn
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

  # https://github.com/alexbers/mtprotoproxy
  mtproxy:
    image: alexbers/mtprotoproxy:stable
    container_name: mtproxy
    ports:
      - "443:443" # internal port define in config_mtproxy_server.py -> PORT
    volumes:
      - ./config_mtproxy_server.py:/home/tgproxy/config.py
      - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
    restart: unless-stopped
